'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='payday_paycheck_first_v4';
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const todayISO=()=>new Date().toISOString().slice(0,10);
const iso=s=>new Date(`${s}T12:00:00`);
const monthKey=s=>String(s).slice(0,7);
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const fmtDate=s=>s?iso(s).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}):'—';
const shortDate=s=>s?iso(s).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'—';
const monthLabel=m=>iso(`${m}-01`).toLocaleDateString(undefined,{month:'long',year:'numeric'});
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));

function addDays(s,n){const d=iso(s);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
function addMonths(s,n){const d=iso(s),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return d.toISOString().slice(0,10)}
function nextSemimonthly(s){const d=iso(s);if(d.getDate()<15)d.setDate(15);else{d.setMonth(d.getMonth()+1);d.setDate(1)}return d.toISOString().slice(0,10)}
function nextPayDate(s,f){if(f==='weekly')return addDays(s,7);if(f==='biweekly')return addDays(s,14);if(f==='semimonthly')return nextSemimonthly(s);return addMonths(s,1)}
function dueDateForMonth(month,day){const [y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate();return `${month}-${String(Math.min(clamp(day,1,31),last)).padStart(2,'0')}`}
function previousMonth(m){return addMonths(`${m}-01`,-1).slice(0,7)}
function nextMonth(m){return addMonths(`${m}-01`,1).slice(0,7)}

const demo=()=>({
 settings:{nextCheckDate:addDays(todayISO(),4),basePay:2184,payFrequency:'biweekly',savingsBuffer:100,protectedCash:150,savingsPct:70,otherPct:30},
 paychecks:[], bills:[
  {id:uid(),name:'Rent',amount:1150,dueDay:1,category:'Housing',priority:1,recurrence:'monthly',allocation:'split',firstCheckPct:70,active:true,notes:''},
  {id:uid(),name:'Electric',amount:125,dueDay:16,category:'Utilities',priority:1,recurrence:'monthly',allocation:'full',firstCheckPct:50,active:true,notes:''},
  {id:uid(),name:'Credit Card',amount:300,dueDay:25,category:'Credit Card',priority:2,recurrence:'monthly',allocation:'split',firstCheckPct:70,active:true,notes:''},
  {id:uid(),name:'Spotify',amount:12,dueDay:12,category:'Subscriptions',priority:3,recurrence:'monthly',allocation:'full',firstCheckPct:50,active:true,notes:''}
 ],
 goals:[{id:uid(),name:'Emergency Fund',target:10000,current:1200,contribution:200,dueDate:'',priority:1,active:true}],
 paidOccurrences:{},selectedPaycheckId:null,monthView:monthKey(todayISO())
});

function migrate(raw){
 const x=raw||demo();
 x.settings=Object.assign({nextCheckDate:'',basePay:0,payFrequency:'biweekly',savingsBuffer:100,protectedCash:150,savingsPct:70,otherPct:30},x.settings||{});
 if(x.settings.leftoverCash!=null&&x.settings.protectedCash==null)x.settings.protectedCash=Number(x.settings.leftoverCash);
 x.bills=(x.bills||[]).map(b=>({id:b.id||uid(),name:b.name||'Bill',amount:Number(b.amount)||0,dueDay:clamp(b.dueDay||(b.dueDate?iso(b.dueDate).getDate():1),1,31),category:b.category||'',priority:clamp(b.priority||1,1,3),recurrence:b.recurrence||'monthly',allocation:b.allocation||'full',firstCheckPct:clamp(b.firstCheckPct??50,0,100),active:b.active!==false,notes:b.notes||'',oneTimeDate:b.oneTimeDate||b.dueDate||''}));
 x.goals=(x.goals||[]).map(g=>({...g,id:g.id||uid(),target:Number(g.target)||0,current:Number(g.current)||0,contribution:Number(g.contribution)||0,priority:Number(g.priority)||3,active:g.active!==false}));
 x.paychecks=(x.paychecks||[]).map(p=>({id:p.id||uid(),date:p.date,amount:Number(p.amount||x.settings.basePay)||0,incomeEntries:Array.isArray(p.incomeEntries)?p.incomeEntries:[...(Number(p.overtime||p.extra||0)?[{id:uid(),type:'Overtime',amount:Number(p.overtime||p.extra),description:''}]:[]),...(Number(p.reimbursement||0)?[{id:uid(),type:'Reimbursement',amount:Number(p.reimbursement),description:''}]:[])],notes:p.notes||''}));
 x.paidOccurrences=x.paidOccurrences||{};x.monthView=x.monthView||monthKey(todayISO());return x;
}
function load(){for(const k of [KEY,'payday_combined_modern_v3_3','payday_combined_modern_v3','payday_combined_modern_v2','payday_combined_modern_v1']){try{const raw=localStorage.getItem(k);if(raw)return migrate(JSON.parse(raw))}catch{}}return demo()}
let state=load();
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('#storageStatus').textContent=`Saved ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),1800)}

function rollNextCheckForward(){let d=state.settings.nextCheckDate;if(!d)return;while(d<todayISO())d=nextPayDate(d,state.settings.payFrequency);state.settings.nextCheckDate=d}
function syncPaySchedule(){
 rollNextCheckForward();const first=state.settings.nextCheckDate;if(!first||!Number(state.settings.basePay))return;
 const old=new Map((state.paychecks||[]).map(p=>[p.date,p]));const end=addMonths(first,12),out=[];let d=first;
 while(d<=end){const p=old.get(d)||{};out.push({id:p.id||uid(),date:d,amount:Number(state.settings.basePay),incomeEntries:p.incomeEntries||[],notes:p.notes||''});d=nextPayDate(d,state.settings.payFrequency)}
 state.paychecks=out;if(!state.selectedPaycheckId||!out.some(p=>p.id===state.selectedPaycheckId))state.selectedPaycheckId=out[0]?.id||null;
}
const checks=()=>[...(state.paychecks||[])].sort((a,b)=>a.date.localeCompare(b.date));
const monthChecks=m=>checks().filter(p=>monthKey(p.date)===m);
const extraIncome=p=>(p.incomeEntries||[]).reduce((s,e)=>s+Number(e.amount||0),0);
const totalIncome=p=>Number(p.amount||state.settings.basePay||0)+extraIncome(p);

function occurrenceKey(b,due){return `${b.id}|${due}`}
function isPaid(b,due){return !!state.paidOccurrences[occurrenceKey(b,due)]}
function setPaid(b,due,val){const k=occurrenceKey(b,due);if(val)state.paidOccurrences[k]=true;else delete state.paidOccurrences[k]}
function monthlyOccurrenceOnOrAfter(date,day){const current=dueDateForMonth(monthKey(date),day);return current>=date?current:dueDateForMonth(nextMonth(monthKey(date)),day)}
function previousOccurrence(b,due){if(b.recurrence==='monthly')return dueDateForMonth(previousMonth(monthKey(due)),b.dueDay);if(b.recurrence==='weekly')return addDays(due,-7);if(b.recurrence==='biweekly')return addDays(due,-14);return checks()[0]?addDays(checks()[0].date,-1):addDays(due,-1)}
function nextOccurrence(b,from){
 if(!b.active)return null;
 if(b.recurrence==='one-time')return b.oneTimeDate&&b.oneTimeDate>=from?b.oneTimeDate:null;
 if(b.recurrence==='monthly')return monthlyOccurrenceOnOrAfter(from,b.dueDay);
 const step=b.recurrence==='weekly'?7:14;let d=dueDateForMonth(monthKey(from),b.dueDay);while(d<from)d=addDays(d,step);return d;
}
function occurrencesBetween(b,start,end){const out=[];let d=nextOccurrence(b,start),guard=0;while(d&&d<=end&&guard++<80){out.push(d);if(b.recurrence==='one-time')break;d=b.recurrence==='monthly'?dueDateForMonth(nextMonth(monthKey(d)),b.dueDay):addDays(d,b.recurrence==='weekly'?7:14)}return out}

function assignmentMap(){
 const all=checks(),map=new Map(all.map(p=>[p.id,[]]));if(!all.length)return map;const start=all[0].date,end=addMonths(all[all.length-1].date,1);
 state.bills.filter(b=>b.active).forEach(b=>occurrencesBetween(b,start,end).forEach(due=>{
  const prev=previousOccurrence(b,due),eligible=all.filter(p=>p.date>prev&&p.date<=due);if(!eligible.length)return;
  if(b.allocation==='split'&&eligible.length>=2){const pct=clamp(b.firstCheckPct??50,0,100)/100;[{p:eligible[0],amt:Number(b.amount)*pct,part:1,total:2,pct:pct*100},{p:eligible[1],amt:Number(b.amount)*(1-pct),part:2,total:2,pct:(1-pct)*100}].forEach(x=>map.get(x.p.id)?.push({...b,dueDate:due,assignedAmount:x.amt,fundingPart:x.part,fundingTotal:x.total,fundingPct:x.pct}))}
  else{const p=eligible[eligible.length-1];map.get(p.id)?.push({...b,dueDate:due,assignedAmount:Number(b.amount),fundingPart:1,fundingTotal:1,fundingPct:100})}
 }));return map;
}
function goalAssignments(p){const n=monthChecks(monthKey(p.date)).length||1;return state.goals.filter(g=>g.active).map(g=>({...g,assignedAmount:Number(g.contribution||0)/n}))}
function plan(p){const bills=assignmentMap().get(p.id)||[],goals=goalAssignments(p),income=totalIncome(p),billTotal=bills.reduce((s,b)=>s+b.assignedAmount,0),goalTotal=goals.reduce((s,g)=>s+g.assignedAmount,0),protectedTotal=Number(state.settings.savingsBuffer||0)+Number(state.settings.protectedCash||0),remaining=income-billTotal-goalTotal-protectedTotal,extra=Math.max(0,remaining);return{bills,goals,income,billTotal,goalTotal,protectedTotal,remaining,alloc:{savings:extra*Number(state.settings.savingsPct||0)/100,other:extra*Number(state.settings.otherPct||0)/100}}}
function currentCheck(){return checks().find(p=>p.date>=todayISO())||checks()[0]||null}
function selectedCheck(){return checks().find(p=>p.id===state.selectedPaycheckId)||currentCheck()}

function showPage(id,title){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$('#pageTitle').textContent=title||({dashboard:'Dashboard',paychecks:'Paychecks',bills:'Bills',monthly:'Monthly',goals:'Goals',settings:'Settings',paycheckDetail:'Paycheck Details'})[id]||'PayDay';$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});updateHeaderAction(id)}
function updateHeaderAction(page){const b=$('#headerAction');if(page==='dashboard'||page==='bills'){b.textContent='Add Bill';b.dataset.action='bill'}else if(page==='goals'){b.textContent='Add Goal';b.dataset.action='goal'}else if(page==='paychecks'){b.textContent='Edit Schedule';b.dataset.action='schedule'}else{b.textContent='Add Bill';b.dataset.action='bill';b.style.display=page==='paycheckDetail'?'none':'';return}b.style.display=''}

function row(label,value,small=''){return `<div class="list-row"><div><strong>${label}</strong>${small?`<small>${small}</small>`:''}</div><strong>${value}</strong></div>`}
function renderDashboard(){const p=currentCheck();if(!p){$('#heroDate').textContent='No check scheduled';$('#heroIncome').textContent=money(0);$('#dashboardBreakdown').innerHTML='<div class="empty-state">Set your pay schedule in Settings.</div>';return}const x=plan(p);$('#heroDate').textContent=fmtDate(p.date);$('#heroIncome').textContent=money(x.income);$('#heroIncomeText').textContent=`Base ${money(p.amount)}${extraIncome(p)?` + ${money(extraIncome(p))} extra income`:''}`;$('#metricBillsDue').textContent=money(x.billTotal);$('#metricBillsCount').textContent=`${x.bills.length} bill funding item${x.bills.length===1?'':'s'}`;$('#metricGoals').textContent=money(x.goalTotal);$('#metricGoalCount').textContent=`${x.goals.length} active goal${x.goals.length===1?'':'s'}`;$('#metricProtected').textContent=money(x.protectedTotal);$('#metricRemaining').textContent=money(x.remaining);$('#metricRemaining').className=x.remaining<0?'negative':'positive';
 $('#dashboardBreakdown').innerHTML=[row('Base pay',money(p.amount)),...(p.incomeEntries||[]).map(e=>row(e.type,`+${money(e.amount)}`,e.description||'')),row('Bills Due',`-${money(x.billTotal)}`,`${x.bills.length} funding items`),row('Goal Contributions',`-${money(x.goalTotal)}`),row('Protected Savings',`-${money(state.settings.savingsBuffer)}`),row('Protected Cash',`-${money(state.settings.protectedCash)}`),`<div class="list-row"><div><strong>Remaining</strong></div><strong class="${x.remaining<0?'negative':'positive'}">${money(x.remaining)}</strong></div>`].join('');
 const upcoming=[];state.bills.filter(b=>b.active).forEach(b=>{const d=nextOccurrence(b,todayISO());if(d)upcoming.push({...b,dueDate:d})});upcoming.sort((a,b)=>a.dueDate.localeCompare(b.dueDate));$('#upcomingBillsList').innerHTML=upcoming.slice(0,6).map(b=>row(b.name,money(b.amount),`Due ${fmtDate(b.dueDate)} · Priority ${b.priority}`)).join('')||'<div class="empty-state">No upcoming bills.</div>';
 $('#dashboardGoals').innerHTML=state.goals.filter(g=>g.active).map(goalCard).join('')||'<div class="empty-state">No active goals.</div>';requestAnimationFrame(renderCharts)}
function renderPaychecks(){let last='';$('#paycheckTimeline').innerHTML=checks().map(p=>{const m=monthKey(p.date),x=plan(p);let h='';if(m!==last){last=m;h=`<div class="month-group"><div class="month-title">${monthLabel(m)}</div>`}const isNext=p.id===currentCheck()?.id;const card=`<div class="check-card ${isNext?'next':''}" data-open-check="${p.id}"><div><span>${isNext?'<span class="pill good">Next check</span>':'Paycheck'}</span><strong>${fmtDate(p.date)}</strong></div><div class="secondary"><span>Income</span><strong>${money(x.income)}</strong></div><div class="secondary"><span>Bills Due</span><strong>${money(x.billTotal)}</strong></div><div class="optional"><span>Goals</span><strong>${money(x.goalTotal)}</strong></div><div class="optional"><span>Remaining</span><strong class="${x.remaining<0?'negative':'positive'}">${money(x.remaining)}</strong></div><button class="small-btn">Open</button></div>`;const nextIndex=checks().findIndex(q=>q.id===p.id)+1;const nextMonthKey=checks()[nextIndex]?monthKey(checks()[nextIndex].date):null;return h+card+(nextMonthKey!==m?'</div>':'')}).join('')||'<div class="empty-state">Set a pay schedule to generate the next 12 months.</div>'}
function renderBills(){$('#billTableBody').innerHTML=state.bills.slice().sort((a,b)=>a.dueDay-b.dueDay).map(b=>`<tr><td><strong>${b.name}</strong><div class="muted">${b.category||'Uncategorized'}</div></td><td>${money(b.amount)}</td><td>Day ${b.dueDay}</td><td>${b.priority}</td><td>${({monthly:'Monthly',weekly:'Weekly',biweekly:'Biweekly','one-time':'One-Time'})[b.recurrence]}</td><td>${b.allocation==='split'?`${b.firstCheckPct}% / ${100-b.firstCheckPct}%`:'Full amount'}</td><td><span class="pill ${b.active?'good':'warn'}">${b.active?'Active':'Inactive'}</span></td><td><div class="row-actions"><button class="small-btn" data-edit-bill="${b.id}">Edit</button><button class="small-btn" data-delete-bill="${b.id}">Delete</button></div></td></tr>`).join('')}
function goalCard(g){const pct=Math.min(100,Number(g.current||0)/Math.max(1,Number(g.target||0))*100);return `<article class="goal-card"><div class="card-title"><div><h4>${g.name}</h4><div class="muted">Priority ${g.priority}${g.dueDate?` · Due ${fmtDate(g.dueDate)}`:''}</div></div><div class="row-actions"><button class="small-btn" data-edit-goal="${g.id}">Edit</button><button class="small-btn" data-delete-goal="${g.id}">Delete</button></div></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="muted">${pct.toFixed(0)}% complete</div><div class="card-stats"><div><span>Current</span><strong>${money(g.current)}</strong></div><div><span>Target</span><strong>${money(g.target)}</strong></div><div><span>Monthly</span><strong>${money(g.contribution)}</strong></div><div><span>Remaining</span><strong>${money(Math.max(0,g.target-g.current))}</strong></div></div></article>`}
function renderGoals(){$('#goalCards').innerHTML=state.goals.slice().sort((a,b)=>a.priority-b.priority).map(goalCard).join('')||'<div class="empty-state">Add your first goal.</div>'}
function renderMonthly(){const m=$('#monthPicker').value||state.monthView||monthKey(todayISO());state.monthView=m;const ps=monthChecks(m),plans=ps.map(plan),income=plans.reduce((s,x)=>s+x.income,0),bills=plans.reduce((s,x)=>s+x.billTotal,0),goals=plans.reduce((s,x)=>s+x.goalTotal,0),remaining=plans.reduce((s,x)=>s+x.remaining,0);$('#monthlySummary').innerHTML=[['Income',income],['Bills Due',bills],['Goals',goals],['Protected',ps.length*(Number(state.settings.savingsBuffer)+Number(state.settings.protectedCash))],['Remaining',remaining]].map(([n,v])=>`<article class="metric-card"><span>${n}</span><strong>${money(v)}</strong></article>`).join('');$('#monthlyChecks').innerHTML=ps.map(p=>{const x=plan(p);return `<div class="list-row" data-open-check="${p.id}"><div><strong>${fmtDate(p.date)}</strong><small>${x.bills.length} bill items · ${x.goals.length} goals</small></div><div><strong>${money(x.income)}</strong><small>Remaining ${money(x.remaining)}</small></div></div>`}).join('')||'<div class="empty-state">No checks in this month.</div>'}
function renderSettings(){const s=state.settings;$('#settingsNextCheckDate').value=s.nextCheckDate||'';$('#settingsBasePay').value=s.basePay||'';$('#settingsPayFrequency').value=s.payFrequency;$('#settingsSavingsBuffer').value=s.savingsBuffer;$('#settingsProtectedCash').value=s.protectedCash;$('#settingsSavingsPct').value=s.savingsPct;$('#settingsOtherPct').value=s.otherPct;$('#monthPicker').value=state.monthView||monthKey(todayISO())}
function renderDetail(){const p=selectedCheck();if(!p)return;state.selectedPaycheckId=p.id;const x=plan(p);$('#detailDate').textContent=fmtDate(p.date);$('#detailIncome').textContent=money(x.income);$('#detailSubtitle').textContent=`Base ${money(p.amount)} · ${p.incomeEntries.length} extra income entr${p.incomeEntries.length===1?'y':'ies'}`;$('#detailIncomeList').innerHTML=[row('Base Pay',money(p.amount),'Standard recurring paycheck'),...(p.incomeEntries||[]).map(e=>`<div class="list-row"><div><strong>${e.type}</strong><small>${e.description||'Individual check adjustment'}</small></div><div class="row-actions"><strong>+${money(e.amount)}</strong><button class="small-btn" data-delete-income="${e.id}">Delete</button></div></div>`)].join('');$('#detailSummary').innerHTML=[['Bills Due',x.billTotal],['Goals',x.goalTotal],['Protected Savings',state.settings.savingsBuffer],['Protected Cash',state.settings.protectedCash],['Extra to Savings',x.alloc.savings],['Extra to Other',x.alloc.other],['Remaining',x.remaining]].map(([n,v])=>`<div><span>${n}</span><strong class="${n==='Remaining'?(v<0?'negative':'positive'):''}">${money(v)}</strong></div>`).join('');$('#detailBills').innerHTML=x.bills.map(b=>`<div class="detail-row"><div class="detail-row-main"><input type="checkbox" data-paid-bill="${b.id}" data-due-date="${b.dueDate}" ${isPaid(b,b.dueDate)?'checked':''}><div><strong>${b.name}</strong><small>Upcoming due date: ${fmtDate(b.dueDate)} · Funding ${b.fundingPart} of ${b.fundingTotal} (${b.fundingPct.toFixed(0)}%) · Priority ${b.priority}</small></div></div><div class="detail-row-amount"><strong>${money(b.assignedAmount)}</strong><small>${isPaid(b,b.dueDate)?'Paid':'Not paid'}</small></div></div>`).join('')||'<div class="empty-state">No bills assigned to this check.</div>';$('#detailGoals').innerHTML=x.goals.map(g=>`<div class="detail-row"><div><strong>${g.name}</strong><small>Monthly contribution split across this month’s checks</small></div><strong>${money(g.assignedAmount)}</strong></div>`).join('')||'<div class="empty-state">No goal contributions.</div>';$('#detailNotes').value=p.notes||''}
function render(){syncPaySchedule();renderDashboard();renderPaychecks();renderBills();renderMonthly();renderGoals();renderSettings();if($('#paycheckDetail').classList.contains('active'))renderDetail();save()}

function openCheck(id){state.selectedPaycheckId=id;renderDetail();showPage('paycheckDetail','Paycheck Details')}
function fillBill(b={}){$('#billId').value=b.id||'';$('#billName').value=b.name||'';$('#billAmount').value=b.amount||'';$('#billDueDay').value=b.dueDay||'';$('#billCategory').value=b.category||'';$('#billPriority').value=b.priority||1;$('#billRecurrence').value=b.recurrence||'monthly';$('#billAllocation').value=b.allocation||'full';$('#billFirstCheckPct').value=b.firstCheckPct??50;$('#billActive').checked=b.active!==false;$('#billNotes').value=b.notes||'';$('#splitPctField').hidden=$('#billAllocation').value!=='split';$('#billModalTitle').textContent=b.id?'Edit Bill':'Add Bill'}
function fillGoal(g={}){$('#goalId').value=g.id||'';$('#goalName').value=g.name||'';$('#goalTarget').value=g.target||'';$('#goalCurrent').value=g.current||0;$('#goalContribution').value=g.contribution||0;$('#goalDueDate').value=g.dueDate||'';$('#goalPriority').value=g.priority||3;$('#goalActive').checked=g.active!==false;$('#goalModalTitle').textContent=g.id?'Edit Goal':'Add Goal'}
function openModal(id){$('#'+id).showModal()}

$('#mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)showPage(b.dataset.page,b.textContent)});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
$('#headerAction').onclick=()=>{const a=$('#headerAction').dataset.action;if(a==='goal'){fillGoal();openModal('goalModal')}else if(a==='schedule')showPage('settings','Settings');else{fillBill();openModal('billModal')}};
$('#dashboardPaycheckCard').onclick=()=>currentCheck()&&openCheck(currentCheck().id);$('#openCurrentDetail').onclick=()=>currentCheck()&&openCheck(currentCheck().id);$('#detailBackBtn').onclick=()=>showPage('paychecks','Paychecks');$('#addBillBtn').onclick=()=>{fillBill();openModal('billModal')};$('#addGoalBtn').onclick=()=>{fillGoal();openModal('goalModal')};$('#editScheduleBtn').onclick=()=>showPage('settings','Settings');
$('#billAllocation').onchange=()=>$('#splitPctField').hidden=$('#billAllocation').value!=='split';$('#monthPicker').onchange=()=>{state.monthView=$('#monthPicker').value;renderMonthly();save()};
$('#addIncomeBtn').onclick=()=>{const p=selectedCheck();if(!p)return;$('#incomeId').value='';$('#incomeType').value='Overtime';$('#incomeAmount').value='';$('#incomeDescription').value='';openModal('incomeModal')};
$('#saveDetailNotes').onclick=()=>{const p=selectedCheck();if(p){p.notes=$('#detailNotes').value.trim();render();toast('Paycheck notes saved')}};

$('#billForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#billId').value||uid(),old=state.bills.find(b=>b.id===id)||{};const obj={...old,id,name:$('#billName').value.trim(),amount:Number($('#billAmount').value),dueDay:clamp($('#billDueDay').value,1,31),category:$('#billCategory').value.trim(),priority:Number($('#billPriority').value),recurrence:$('#billRecurrence').value,allocation:$('#billAllocation').value,firstCheckPct:clamp($('#billFirstCheckPct').value||50,0,100),active:$('#billActive').checked,notes:$('#billNotes').value.trim()};const i=state.bills.findIndex(b=>b.id===id);i>=0?state.bills[i]=obj:state.bills.push(obj);$('#billModal').close();render();toast('Bill saved')});
$('#goalForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#goalId').value||uid(),obj={id,name:$('#goalName').value.trim(),target:Number($('#goalTarget').value),current:Number($('#goalCurrent').value||0),contribution:Number($('#goalContribution').value||0),dueDate:$('#goalDueDate').value,priority:Number($('#goalPriority').value),active:$('#goalActive').checked};const i=state.goals.findIndex(g=>g.id===id);i>=0?state.goals[i]=obj:state.goals.push(obj);$('#goalModal').close();render();toast('Goal saved')});
$('#incomeForm').addEventListener('submit',e=>{e.preventDefault();const p=selectedCheck();if(!p)return;p.incomeEntries.push({id:uid(),type:$('#incomeType').value,amount:Number($('#incomeAmount').value),description:$('#incomeDescription').value.trim()});$('#incomeModal').close();render();renderDetail();toast('Income added to this paycheck')});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const savings=Number($('#settingsSavingsPct').value),other=Number($('#settingsOtherPct').value);if(savings+other!==100){toast('Savings and Other percentages must total 100%');return}state.settings={nextCheckDate:$('#settingsNextCheckDate').value,basePay:Number($('#settingsBasePay').value),payFrequency:$('#settingsPayFrequency').value,savingsBuffer:Number($('#settingsSavingsBuffer').value||0),protectedCash:Number($('#settingsProtectedCash').value||0),savingsPct:savings,otherPct:other};syncPaySchedule();render();toast('Settings saved and schedule regenerated')});

document.addEventListener('click',e=>{const t=e.target.closest('button,[data-open-check],[data-paid-bill]');if(!t)return;let id;if(id=t.dataset.openCheck)openCheck(id);else if(id=t.dataset.editBill){fillBill(state.bills.find(b=>b.id===id));openModal('billModal')}else if(id=t.dataset.deleteBill){if(confirm('Delete this bill?')){state.bills=state.bills.filter(b=>b.id!==id);render()}}else if(id=t.dataset.editGoal){fillGoal(state.goals.find(g=>g.id===id));openModal('goalModal')}else if(id=t.dataset.deleteGoal){if(confirm('Delete this goal?')){state.goals=state.goals.filter(g=>g.id!==id);render()}}else if(id=t.dataset.deleteIncome){const p=selectedCheck();if(p){p.incomeEntries=p.incomeEntries.filter(x=>x.id!==id);render();renderDetail()}}else if(t.matches('[data-close-dialog]')){e.preventDefault();t.closest('dialog')?.close()}});
document.addEventListener('change',e=>{if(e.target.dataset.paidBill){const b=state.bills.find(x=>x.id===e.target.dataset.paidBill);if(b){setPaid(b,e.target.dataset.dueDate,e.target.checked);render();renderDetail();toast(e.target.checked?'Bill marked paid':'Bill marked unpaid')}}});
$$('dialog').forEach(d=>d.addEventListener('click',e=>{const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}));

$('#exportBtn').onclick=()=>{const a=document.createElement('a'),blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='payday-v4-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{try{state=migrate(JSON.parse(await e.target.files[0].text()));render();toast('Backup imported')}catch{toast('Invalid backup file')}};
$('#demoBtn').onclick=()=>{if(confirm('Replace current data with demo data?')){state=demo();render();toast('Demo loaded')}};$('#resetBtn').onclick=()=>{if(confirm('Delete all app data?')){state=demo();state.bills=[];state.goals=[];state.settings.nextCheckDate='';state.settings.basePay=0;state.paychecks=[];render();toast('Data reset')}};

function canvasSetup(canvas){if(!canvas)return null;const r=canvas.getBoundingClientRect(),dpr=Math.max(1,devicePixelRatio||1);canvas.width=Math.floor(r.width*dpr);canvas.height=Math.floor(r.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w:r.width,h:r.height}}
function drawBars(canvas,items){const c=canvasSetup(canvas);if(!c)return;const{ctx,w,h}=c;ctx.clearRect(0,0,w,h);const pad={l:48,r:12,t:16,b:40},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=Math.max(1,...items.map(i=>i.value));ctx.font='11px system-ui';ctx.fillStyle='#9fb0c8';for(let i=0;i<=4;i++){const y=pad.t+ch-ch*i/4;ctx.strokeStyle='rgba(159,176,200,.16)';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.textAlign='right';ctx.fillText(money(max*i/4).replace('.00',''),pad.l-6,y+4)}const gap=9,bw=Math.max(22,(cw-gap*(items.length+1))/Math.max(items.length,1));items.forEach((it,i)=>{const x=pad.l+gap+i*(bw+gap),bh=ch*it.value/max,y=pad.t+ch-bh,g=ctx.createLinearGradient(0,y,0,pad.t+ch);g.addColorStop(0,'#22d3ee');g.addColorStop(1,'#3b82f6');ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(x,y,bw,bh,7);ctx.fill();ctx.fillStyle='#cbd5e1';ctx.textAlign='center';ctx.fillText(it.label,x+bw/2,h-17)})}
function drawDonut(canvas,items){const c=canvasSetup(canvas);if(!c)return;const{ctx,w,h}=c;ctx.clearRect(0,0,w,h);const total=items.reduce((s,i)=>s+i.value,0);if(!total){ctx.fillStyle='#9fb0c8';ctx.textAlign='center';ctx.fillText('No current allocation',w/2,h/2);return}const colors=['#3b82f6','#22d3ee','#34d399','#fbbf24','#a78bfa'];let a=-Math.PI/2;const cx=w*.34,cy=h*.5,r=Math.min(w,h)*.29,inner=r*.58;items.forEach((it,i)=>{const n=a+it.value/total*Math.PI*2;ctx.beginPath();ctx.arc(cx,cy,r,a,n);ctx.arc(cx,cy,inner,n,a,true);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();a=n});ctx.fillStyle='#f8fafc';ctx.font='700 18px system-ui';ctx.textAlign='center';ctx.fillText(money(total),cx,cy+5);items.forEach((it,i)=>{const y=48+i*32,x=w*.63;ctx.fillStyle=colors[i%colors.length];ctx.fillRect(x,y-10,10,10);ctx.fillStyle='#cbd5e1';ctx.textAlign='left';ctx.font='12px system-ui';ctx.fillText(`${it.label} ${money(it.value)}`,x+16,y)})}
function renderCharts(){const p=currentCheck();drawBars($('#cashFlowChart'),checks().slice(0,6).map(q=>({label:shortDate(q.date),value:totalIncome(q)})));if(p){const x=plan(p);drawDonut($('#allocationChart'),[{label:'Bills',value:x.billTotal},{label:'Goals',value:x.goalTotal},{label:'Savings',value:Number(state.settings.savingsBuffer)},{label:'Cash',value:Number(state.settings.protectedCash)},{label:'Remaining',value:Math.max(0,x.remaining)}])}}
window.addEventListener('resize',()=>requestAnimationFrame(renderCharts));
$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
render();
