const KEY='payday_combined_modern_v2';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const iso=d=>new Date(d+'T12:00:00');
const todayISO=()=>new Date().toISOString().slice(0,10);
const monthKey=d=>d.slice(0,7);
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());

const demo=()=>({settings:{planningMonth:'2026-07',payFrequency:'biweekly',savingsBuffer:100,leftoverCash:150,savingsPct:70,otherPct:30,rentAdvance:true},paychecks:[{id:uid(),date:'2026-07-03',amount:2457,extra:89,notes:'Regular pay + reimbursement'},{id:uid(),date:'2026-07-17',amount:2184,extra:0,notes:''},{id:uid(),date:'2026-07-31',amount:2184,extra:0,notes:''}],bills:[
{id:uid(),name:'Rent',amount:1150,dueDate:'2026-08-01',category:'Housing',priority:1,recurrence:'monthly',allocation:'split',active:true,paid:false,notes:'Plan one month ahead'},
{id:uid(),name:'Personal Loan',amount:444,dueDate:'2026-07-28',category:'Debt',priority:1,recurrence:'monthly',allocation:'full',active:true,paid:false,notes:''},
{id:uid(),name:'Government Loan',amount:193,dueDate:'2026-07-10',category:'Debt',priority:1,recurrence:'monthly',allocation:'full',active:true,paid:false,notes:''},
{id:uid(),name:'Car Insurance',amount:215,dueDate:'2026-07-12',category:'Insurance',priority:1,recurrence:'monthly',allocation:'full',active:true,paid:false,notes:''},
{id:uid(),name:'Electric',amount:125,dueDate:'2026-07-16',category:'Utility',priority:2,recurrence:'monthly',allocation:'full',active:true,paid:false,notes:''},
{id:uid(),name:'Spotify',amount:12,dueDate:'2026-07-12',category:'Subscription',priority:3,recurrence:'monthly',allocation:'full',active:true,paid:false,notes:''}],goals:[{id:uid(),name:'Emergency Fund',target:10000,current:1000,contribution:200,dueDate:'',priority:1,active:true},{id:uid(),name:'Wedding',target:3653,current:1800,contribution:350,dueDate:'2027-05-24',priority:2,active:true}],selectedPaycheckId:null});
let state=load();
function load(){try{const current=localStorage.getItem(KEY);const legacy=localStorage.getItem('payday_combined_modern_v1');const loaded=JSON.parse(current||legacy||'null')||demo();loaded.settings=Object.assign({planningMonth:new Date().toISOString().slice(0,7),payFrequency:'biweekly',savingsBuffer:100,leftoverCash:150,savingsPct:70,otherPct:30,rentAdvance:true},loaded.settings||{});delete loaded.settings.debtPct;delete loaded.debts;return loaded}catch{return demo()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('#storageStatus').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function monthPaychecks(month=state.settings.planningMonth){return state.paychecks.filter(p=>monthKey(p.date)===month).sort((a,b)=>a.date.localeCompare(b.date))}
function totalIncome(p){return Number(p.amount)+Number(p.extra||0)}
function dueInPlanningMonth(b,month=state.settings.planningMonth){if(!b.active)return false; const target=b.name.toLowerCase()==='rent'&&state.settings.rentAdvance?nextMonth(month):month; return monthKey(b.dueDate)===target}
function nextMonth(m){const [y,mo]=m.split('-').map(Number);return new Date(y,mo,1).toISOString().slice(0,7)}
function addDays(date,days){const d=iso(date);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function addMonths(date,months){const d=iso(date),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+months);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return d.toISOString().slice(0,10)}
function nextSemimonthly(date){const d=iso(date),day=d.getDate();if(day<15){d.setDate(15)}else{d.setMonth(d.getMonth()+1,1)}return d.toISOString().slice(0,10)}
function generatePaySchedule(base,frequency){const end=addMonths(base.date,12),out=[];let date=base.date;while(date<=end){out.push({...base,id:out.length?uid():base.id,date});if(frequency==='weekly')date=addDays(date,7);else if(frequency==='biweekly')date=addDays(date,14);else if(frequency==='semimonthly')date=nextSemimonthly(date);else if(frequency==='monthly')date=addMonths(date,1);else break}return out}

function billStatus(b){if(b.paid)return['Paid','good'];if(iso(b.dueDate)<new Date())return['Overdue','bad'];return['Due','warn']}
function assignedBillAmounts(month=state.settings.planningMonth){const checks=monthPaychecks(month);const map=new Map(checks.map(p=>[p.id,[]]));if(!checks.length)return map;
 state.bills.filter(b=>dueInPlanningMonth(b,month)).forEach(b=>{if(b.allocation==='split'){const amount=Number(b.amount)/checks.length;checks.forEach(p=>map.get(p.id).push({...b,assignedAmount:amount}))}else{let idx=checks.findLastIndex(p=>p.date<=b.dueDate);if(idx<0)idx=0;map.get(checks[idx].id).push({...b,assignedAmount:Number(b.amount)})}});return map}
function goalPerCheck(month=state.settings.planningMonth){const n=monthPaychecks(month).length||1;return state.goals.filter(g=>g.active).map(g=>({...g,assignedAmount:Number(g.contribution||0)/n}))}
function paycheckPlan(p,month=state.settings.planningMonth){const bills=assignedBillAmounts(month).get(p.id)||[];const goals=goalPerCheck(month);const income=totalIncome(p);const billTotal=bills.reduce((s,b)=>s+b.assignedAmount,0);const goalTotal=goals.reduce((s,g)=>s+g.assignedAmount,0);const afterBillsGoals=income-billTotal-goalTotal;const afterProtected=afterBillsGoals-state.settings.savingsBuffer-state.settings.leftoverCash;const extra=Math.max(0,afterProtected);return{bills,goals,income,billTotal,goalTotal,afterBillsGoals,remaining:afterProtected,alloc:{savings:extra*state.settings.savingsPct/100,other:extra*state.settings.otherPct/100}}}
function render(){renderDashboard();renderPaychecks();renderBills();renderMonthly();renderGoals();renderSettings();save();requestAnimationFrame(renderCharts)}
function renderDashboard(){const checks=monthPaychecks();const next=checks.find(p=>p.date>=todayISO())||checks[0];$('#metricNextPaycheck').textContent=next?money(totalIncome(next)):'$0.00';$('#metricNextPaycheckDate').textContent=next?new Date(next.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'No paycheck scheduled';const upcoming=state.bills.filter(b=>dueInPlanningMonth(b)&&!b.paid);$('#metricUpcomingBills').textContent=money(upcoming.reduce((s,b)=>s+Number(b.amount),0));$('#metricUpcomingBillsCount').textContent=`${upcoming.length} unpaid bills`;$('#metricAvailable').textContent=money(next?paycheckPlan(next).remaining:0);const activeGoals=state.goals.filter(g=>g.active);$('#metricGoalTotal').textContent=money(activeGoals.reduce((s,g)=>s+Number(g.contribution||0),0));$('#metricGoalCount').textContent=`${activeGoals.length} active goals`;
 const box=$('#dashboardPaycheckPlan');if(!next)box.innerHTML='<div class="empty-state">Add a paycheck to begin.</div>';else{const x=paycheckPlan(next);box.innerHTML=`<div class="list-row"><span>Income</span><strong>${money(x.income)}</strong></div><div class="list-row"><span>Bills</span><strong>${money(x.billTotal)}</strong></div><div class="list-row"><span>Goals</span><strong>${money(x.goalTotal)}</strong></div><div class="list-row"><span>Protected savings + cash</span><strong>${money(state.settings.savingsBuffer+state.settings.leftoverCash)}</strong></div><div class="list-row"><span>Remaining</span><strong class="${x.remaining<0?'negative':'positive'}">${money(x.remaining)}</strong></div>`}
 const paid=state.bills.filter(b=>dueInPlanningMonth(b)&&b.paid), due=state.bills.filter(b=>dueInPlanningMonth(b)&&!b.paid);$('#dashboardBillStatus').innerHTML=`<div class="list-row"><span>Paid</span><strong>${paid.length}</strong></div><div class="list-row"><span>Remaining</span><strong>${due.length}</strong></div><div class="list-row"><span>Paid value</span><strong>${money(paid.reduce((s,b)=>s+Number(b.amount),0))}</strong></div><div class="list-row"><span>Unpaid value</span><strong>${money(due.reduce((s,b)=>s+Number(b.amount),0))}</strong></div>`;
 const totals=[1,2,3].map(pr=>state.bills.filter(b=>dueInPlanningMonth(b)&&b.priority===pr).reduce((s,b)=>s+Number(b.amount),0));$('#waterfallSummary').innerHTML=[['Priority 1',totals[0]],['Priority 2',totals[1]],['Priority 3',totals[2]],['Goals',state.goals.filter(g=>g.active).reduce((s,g)=>s+Number(g.contribution),0)],['Protected',checks.length*(state.settings.savingsBuffer+state.settings.leftoverCash)]].map(([n,v])=>`<div class="waterfall-row"><span>${n}</span><strong>${money(v)}</strong></div>`).join('');
 $('#dashboardGoals').innerHTML=state.goals.filter(g=>g.active).map(goalCard).join('')||'<div class="empty-state">No active goals.</div>'}
function renderPaychecks(){const body=$('#paycheckTableBody');const map=assignedBillAmounts();body.innerHTML=monthPaychecks().map(p=>{const x=paycheckPlan(p);return`<tr data-id="${p.id}"><td>${fmtDate(p.date)}</td><td>${money(p.amount)}</td><td>${money(p.extra)}</td><td><strong>${money(x.income)}</strong></td><td>${money(x.billTotal)}</td><td>${money(x.goalTotal)}</td><td class="${x.remaining<0?'negative':'positive'}">${money(x.remaining)}</td><td><div class="row-actions"><button class="small-btn" data-select-paycheck="${p.id}">View</button><button class="small-btn" data-edit-paycheck="${p.id}">Edit</button><button class="small-btn" data-delete-paycheck="${p.id}">Delete</button></div></td></tr>`}).join('');if(!state.selectedPaycheckId&&monthPaychecks()[0])state.selectedPaycheckId=monthPaychecks()[0].id;renderSelectedPaycheck()}
function renderSelectedPaycheck(){const p=state.paychecks.find(x=>x.id===state.selectedPaycheckId), el=$('#selectedPaycheckBreakdown'), dateLabel=$('#selectedPaycheckDate');if(!p){el.className='empty-state';el.textContent='Select a paycheck to view its plan.';if(dateLabel)dateLabel.textContent='Select a paycheck to view its plan.';return}if(dateLabel)dateLabel.textContent='Currently selected: '+fmtDate(p.date);const x=paycheckPlan(p);el.className='paycheck-breakdown';const groups=[1,2,3].map(pr=>{const items=x.bills.filter(b=>b.priority===pr);return`<div class="priority-group"><div class="priority-title">Priority ${pr} — ${money(items.reduce((s,b)=>s+b.assignedAmount,0))}</div>${items.length?items.map(b=>`<div class="priority-item"><div><strong>${b.name}</strong><div class="muted">Due ${fmtDate(b.dueDate)}</div></div><div class="inline-actions"><strong>${money(b.assignedAmount)}</strong><input class="check-toggle" type="checkbox" data-toggle-bill="${b.id}" ${b.paid?'checked':''}></div></div>`).join(''):'<div class="priority-item muted">No bills in this priority</div>'}</div>`}).join('');el.innerHTML=`<div class="metric-grid compact"><article class="metric-card"><span>Income</span><strong>${money(x.income)}</strong></article><article class="metric-card"><span>Bills + Goals</span><strong>${money(x.billTotal+x.goalTotal)}</strong></article><article class="metric-card"><span>After Rules</span><strong class="${x.remaining<0?'negative':'positive'}">${money(x.remaining)}</strong></article></div>${groups}<div class="priority-group"><div class="priority-title">Goals — ${money(x.goalTotal)}</div>${x.goals.map(g=>`<div class="priority-item"><span>${g.name}</span><strong>${money(g.assignedAmount)}</strong></div>`).join('')||'<div class="priority-item muted">No goals assigned</div>'}</div><div class="allocation-grid"><div class="allocation-box"><span>Extra to savings</span><strong>${money(x.alloc.savings)}</strong></div><div class="allocation-box"><span>Extra to other</span><strong>${money(x.alloc.other)}</strong></div></div>`}
function renderBills(){const f=$('#billFilter').value||'all';const rows=state.bills.filter(b=>{const s=billStatus(b)[0].toLowerCase();return f==='all'||(f==='paid'&&b.paid)||(f==='unpaid'&&!b.paid)||(f==='overdue'&&s==='overdue')});$('#billTableBody').innerHTML=rows.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(b=>{const [s,c]=billStatus(b);return`<tr><td><span class="status ${c}">${s}</span></td><td><strong>${b.name}</strong><div class="muted">${b.category||'Uncategorized'}</div></td><td>${money(b.amount)}</td><td>${fmtDate(b.dueDate)}</td><td>${b.priority}</td><td>${label(b.recurrence)}</td><td>${b.allocation==='split'?'Split':'Full'}</td><td><input class="check-toggle" type="checkbox" data-toggle-bill="${b.id}" ${b.paid?'checked':''}></td><td><div class="row-actions"><button class="small-btn" data-edit-bill="${b.id}">Edit</button><button class="small-btn" data-delete-bill="${b.id}">Delete</button></div></td></tr>`}).join('')}
function renderMonthly(){const month=$('#monthPicker').value||state.settings.planningMonth;const checks=monthPaychecks(month);const plans=checks.map(p=>paycheckPlan(p,month));const income=plans.reduce((s,x)=>s+x.income,0), bills=plans.reduce((s,x)=>s+x.billTotal,0), goals=plans.reduce((s,x)=>s+x.goalTotal,0);$('#monthlySummary').innerHTML=[['Income',income],['Bills',bills],['Goals',goals],['Protected Savings',checks.length*state.settings.savingsBuffer],['Protected Cash',checks.length*state.settings.leftoverCash],['Remaining',plans.reduce((s,x)=>s+x.remaining,0)]].map(([n,v])=>`<article class="metric-card"><span>${n}</span><strong>${money(v)}</strong></article>`).join('');$('#monthlyPaycheckCards').innerHTML=checks.map(p=>{const x=paycheckPlan(p,month);return`<div class="list-row"><div><strong>${fmtDate(p.date)}</strong><div class="muted">${x.bills.length} bills · ${x.goals.length} goals</div></div><div><strong>${money(x.income)}</strong><div class="muted">Remaining ${money(x.remaining)}</div></div></div>`}).join('')||'<div class="empty-state">No paychecks in this month.</div>'}
function goalCard(g){const pct=Math.min(100,(Number(g.current)/Number(g.target||1))*100);return`<article class="goal-card"><div class="card-title"><div><h4>${g.name}</h4><div class="muted">Priority ${g.priority}${g.dueDate?' · Due '+fmtDate(g.dueDate):''}</div></div><div class="row-actions"><button class="small-btn" data-edit-goal="${g.id}">Edit</button><button class="small-btn" data-delete-goal="${g.id}">Delete</button></div></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="muted">${pct.toFixed(0)}% complete</div><div class="card-stats"><div><span>Current</span><strong>${money(g.current)}</strong></div><div><span>Target</span><strong>${money(g.target)}</strong></div><div><span>Monthly</span><strong>${money(g.contribution)}</strong></div><div><span>Remaining</span><strong>${money(Math.max(0,g.target-g.current))}</strong></div></div></article>`}
function renderGoals(){$('#goalCards').innerHTML=state.goals.sort((a,b)=>a.priority-b.priority).map(goalCard).join('')||'<div class="empty-state">Add your first goal.</div>'}
function renderSettings(){const s=state.settings;$('#settingsPlanningMonth').value=s.planningMonth;$('#settingsPayFrequency').value=s.payFrequency;$('#settingsSavingsBuffer').value=s.savingsBuffer;$('#settingsLeftoverCash').value=s.leftoverCash;$('#settingsSavingsPct').value=s.savingsPct;$('#settingsOtherPct').value=s.otherPct;$('#settingsRentAdvance').checked=s.rentAdvance;$('#monthPicker').value=$('#monthPicker').value||s.planningMonth}
function fmtDate(d){return d?new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—'}function label(s){return({monthly:'Monthly',weekly:'Weekly',biweekly:'Bi-Weekly','one-time':'One-Time'})[s]||s}
function openModal(id){$('#'+id).showModal()}
function fillBill(b={}){$('#billId').value=b.id||'';$('#billName').value=b.name||'';$('#billAmount').value=b.amount||'';$('#billDueDate').value=b.dueDate||'';$('#billCategory').value=b.category||'';$('#billPriority').value=b.priority||1;$('#billRecurrence').value=b.recurrence||'monthly';$('#billAllocation').value=b.allocation||'full';$('#billActive').checked=b.active!==false;$('#billPaid').checked=!!b.paid;$('#billNotes').value=b.notes||''}
function fillPaycheck(p={}){$('#paycheckId').value=p.id||'';$('#paycheckDate').value=p.date||'';$('#paycheckAmount').value=p.amount||'';$('#paycheckExtra').value=p.extra||0;$('#paycheckNotes').value=p.notes||''}
function fillGoal(g={}){$('#goalId').value=g.id||'';$('#goalName').value=g.name||'';$('#goalTarget').value=g.target||'';$('#goalCurrent').value=g.current||0;$('#goalContribution').value=g.contribution||0;$('#goalDueDate').value=g.dueDate||'';$('#goalPriority').value=g.priority||3;$('#goalActive').checked=g.active!==false}

$('#mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(!b)return;$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page).classList.add('active');$('#pageTitle').textContent=b.textContent;$('#sidebar').classList.remove('open')});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
$$('[data-open]').forEach(b=>b.onclick=()=>{const id=b.dataset.open;if(id==='billModal')fillBill();if(id==='paycheckModal')fillPaycheck();if(id==='goalModal')fillGoal();openModal(id)});
$('#quickAddBill').onclick=()=>{fillBill();openModal('billModal')};$('#quickAddPaycheck').onclick=()=>{fillPaycheck();openModal('paycheckModal')};
$('#billForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#billId').value||uid();const obj={id,name:$('#billName').value.trim(),amount:+$('#billAmount').value,dueDate:$('#billDueDate').value,category:$('#billCategory').value.trim(),priority:+$('#billPriority').value,recurrence:$('#billRecurrence').value,allocation:$('#billAllocation').value,active:$('#billActive').checked,paid:$('#billPaid').checked,notes:$('#billNotes').value.trim()};const i=state.bills.findIndex(x=>x.id===id);i>=0?state.bills[i]=obj:state.bills.push(obj);$('#billModal').close();render();toast('Bill saved')});
$('#paycheckForm').addEventListener('submit',e=>{e.preventDefault();const existingId=$('#paycheckId').value;const base={id:existingId||uid(),date:$('#paycheckDate').value,amount:+$('#paycheckAmount').value,extra:+$('#paycheckExtra').value,notes:$('#paycheckNotes').value.trim()};if(existingId){const i=state.paychecks.findIndex(x=>x.id===existingId);if(i>=0)state.paychecks[i]=base;state.selectedPaycheckId=existingId;$('#paycheckModal').close();render();toast('Selected paycheck updated');return}const generated=generatePaySchedule(base,state.settings.payFrequency);let added=0;generated.forEach((p,index)=>{if(!state.paychecks.some(x=>x.date===p.date)){state.paychecks.push({...p,extra:index===0?base.extra:0,notes:index===0?base.notes:''});added++}});state.selectedPaycheckId=(state.paychecks.find(x=>x.date===base.date)||base).id;$('#paycheckModal').close();render();toast(added>1?`${added} paychecks scheduled for the next 12 months`:'Paycheck saved')});
$('#goalForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#goalId').value||uid();const obj={id,name:$('#goalName').value.trim(),target:+$('#goalTarget').value,current:+$('#goalCurrent').value,contribution:+$('#goalContribution').value,dueDate:$('#goalDueDate').value,priority:+$('#goalPriority').value,active:$('#goalActive').checked};const i=state.goals.findIndex(x=>x.id===id);i>=0?state.goals[i]=obj:state.goals.push(obj);$('#goalModal').close();render();toast('Goal saved')});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const total=+$('#settingsSavingsPct').value+ +$('#settingsOtherPct').value;if(total!==100){toast('Allocation percentages must total 100%');return}state.settings={planningMonth:$('#settingsPlanningMonth').value,payFrequency:$('#settingsPayFrequency').value,savingsBuffer:+$('#settingsSavingsBuffer').value,leftoverCash:+$('#settingsLeftoverCash').value,savingsPct:+$('#settingsSavingsPct').value,otherPct:+$('#settingsOtherPct').value,rentAdvance:$('#settingsRentAdvance').checked};$('#monthPicker').value=state.settings.planningMonth;render();toast('Rules saved')});
$('#billFilter').onchange=renderBills;$('#monthPicker').onchange=renderMonthly;
document.addEventListener('click',e=>{const t=e.target;let id;if(id=t.dataset.selectPaycheck){state.selectedPaycheckId=id;renderSelectedPaycheck()}else if(id=t.dataset.editPaycheck){fillPaycheck(state.paychecks.find(x=>x.id===id));openModal('paycheckModal')}else if(id=t.dataset.deletePaycheck){if(confirm('Delete this paycheck?')){state.paychecks=state.paychecks.filter(x=>x.id!==id);render()}}else if(id=t.dataset.editBill){fillBill(state.bills.find(x=>x.id===id));openModal('billModal')}else if(id=t.dataset.deleteBill){if(confirm('Delete this bill?')){state.bills=state.bills.filter(x=>x.id!==id);render()}}else if(id=t.dataset.editGoal){fillGoal(state.goals.find(x=>x.id===id));openModal('goalModal')}else if(id=t.dataset.deleteGoal){if(confirm('Delete this goal?')){state.goals=state.goals.filter(x=>x.id!==id);render()}}});
document.addEventListener('change',e=>{const id=e.target.dataset.toggleBill;if(id){const b=state.bills.find(x=>x.id===id);if(b){b.paid=e.target.checked;render();toast(b.paid?'Bill marked paid':'Bill marked unpaid')}}});
function stepCheck(dir){const c=monthPaychecks();if(!c.length)return;let i=c.findIndex(x=>x.id===state.selectedPaycheckId);i=Math.max(0,Math.min(c.length-1,i+dir));state.selectedPaycheckId=c[i].id;renderSelectedPaycheck()}$('#prevCheck').onclick=()=>stepCheck(-1);$('#nextCheck').onclick=()=>stepCheck(1);
$('#exportJsonBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='payday-combined-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#importJsonInput').onchange=async e=>{try{state=JSON.parse(await e.target.files[0].text());render();toast('Backup imported')}catch{toast('Invalid backup file')}};
$('#loadDemoBtn').onclick=()=>{if(confirm('Replace current data with demo data?')){state=demo();render();toast('Demo data loaded')}};$('#resetDataBtn').onclick=()=>{if(confirm('Delete all app data?')){state={...demo(),paychecks:[],bills:[],goals:[],selectedPaycheckId:null};render();toast('All data reset')}};

function setupCanvas(canvas){if(!canvas)return null;const rect=canvas.getBoundingClientRect(),ratio=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(rect.width*ratio));canvas.height=Math.max(1,Math.floor(rect.height*ratio));const ctx=canvas.getContext('2d');ctx.setTransform(ratio,0,0,ratio,0,0);return{ctx,w:rect.width,h:rect.height}}
function drawBarChart(canvas,items){const c=setupCanvas(canvas);if(!c)return;const{ctx,w,h}=c;ctx.clearRect(0,0,w,h);const pad={l:56,r:16,t:18,b:42},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,max=Math.max(1,...items.map(x=>x.value));ctx.font='12px system-ui';ctx.fillStyle='#94a3b8';ctx.textAlign='right';for(let i=0;i<=4;i++){const y=pad.t+ch-(ch*i/4);ctx.strokeStyle='rgba(148,163,184,.15)';ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillText(money(max*i/4).replace('.00',''),pad.l-8,y+4)}const gap=10,bw=Math.max(18,(cw-gap*(items.length+1))/Math.max(1,items.length));items.forEach((it,i)=>{const x=pad.l+gap+i*(bw+gap),bh=ch*(it.value/max),y=pad.t+ch-bh;const g=ctx.createLinearGradient(0,y,0,pad.t+ch);g.addColorStop(0,'#67e8f9');g.addColorStop(1,'#42a5f5');ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(x,y,bw,bh,7);ctx.fill();ctx.fillStyle='#cbd5e1';ctx.textAlign='center';ctx.fillText(it.label,x+bw/2,h-18)})}
function drawDonut(canvas,items){const c=setupCanvas(canvas);if(!c)return;const{ctx,w,h}=c;ctx.clearRect(0,0,w,h);const total=items.reduce((s,x)=>s+x.value,0);if(!total){ctx.fillStyle='#94a3b8';ctx.textAlign='center';ctx.font='14px system-ui';ctx.fillText('No bills in this month',w/2,h/2);return}const colors=['#42a5f5','#67e8f9','#34d399','#fbbf24','#fb7185','#a78bfa','#f97316'];const cx=w*.34,cy=h*.5,r=Math.min(w,h)*.28,inner=r*.58;let a=-Math.PI/2;items.forEach((it,i)=>{const n=a+it.value/total*Math.PI*2;ctx.beginPath();ctx.arc(cx,cy,r,a,n);ctx.arc(cx,cy,inner,n,a,true);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();a=n});ctx.fillStyle='#f4f7fb';ctx.textAlign='center';ctx.font='700 18px system-ui';ctx.fillText(money(total),cx,cy+5);ctx.font='12px system-ui';ctx.fillStyle='#94a3b8';ctx.fillText('Monthly bills',cx,cy+24);const lx=w*.63;items.slice(0,6).forEach((it,i)=>{const y=36+i*34;ctx.fillStyle=colors[i%colors.length];ctx.fillRect(lx,y-10,11,11);ctx.fillStyle='#cbd5e1';ctx.textAlign='left';ctx.font='12px system-ui';ctx.fillText(it.label,lx+18,y);ctx.fillStyle='#94a3b8';ctx.fillText(money(it.value),lx+18,y+15)})}
function renderCharts(){const checks=monthPaychecks();drawBarChart($('#cashFlowChart'),checks.slice(0,8).map((p,i)=>{const x=paycheckPlan(p);return{label:new Date(p.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}),value:Math.max(0,x.income)}}));const categories={};state.bills.filter(b=>dueInPlanningMonth(b)).forEach(b=>{const k=b.category||'Other';categories[k]=(categories[k]||0)+Number(b.amount||0)});drawDonut($('#categoryChart'),Object.entries(categories).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value))}
window.addEventListener('resize',()=>requestAnimationFrame(renderCharts));
document.addEventListener('click',e=>{const close=e.target.closest('[data-close-dialog]');if(close){e.preventDefault();close.closest('dialog')?.close()}});
$$('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}));

$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js');render();
